ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Models/Product.cs
using System;
using System.Collections.Generic;

namespace ProjectPRN221_Supermarket.Models
{
    public partial class Product
    {
        public Product()
        {
            PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            SalesOrderItems = new HashSet<SalesOrderItem>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal UnitPrice { get; set; }
        public int QuantityInStock { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public int? CategoryId { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
    }
}

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using ProjectPRN221_Supermarket.Hubs;
using ProjectPRN221_Supermarket.Models;
using ProjectPRN221_Supermarket.Repository;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ProjectPRN221_Supermarket.Pages.Products
{
    public class AddModel : PageModel
    {
        IProductRepository _productRepository;
        SupermarketDBContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IHubContext<HubServer> _hubContext;

        public AddModel(IProductRepository productRepository, SupermarketDBContext context, IHttpContextAccessor httpContextAccessor, IHubContext<HubServer> hubContext)
        {
            _productRepository = productRepository;
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _hubContext = hubContext;
        }

        [BindProperty]
        public Product Product { get; set; }

        [BindProperty]
        public DateTime ExpirationDate { get; set; }

        [BindProperty]
        public int SelectedSupplier { get; set; }

        [BindProperty]
        public decimal PurchaseOrderUnitPrice { get; set; }

        public List<Category> Categories { get; set; }
        public List<Supplier> Suppliers { get; set; }

        public IActionResult OnGet()
        {
            var cashierId = _httpContextAccessor.HttpContext.Session.GetString("CashierId");

            // Kiểm tra xem có thông tin người dùng trong phiên không
            if (string.IsNullOrEmpty(cashierId))
            {
                return Redirect("/Login");
            }
            Categories = _context.Categories.ToList();
            Suppliers = _context.Suppliers.ToList(); 
            return Page();
        }

        public IActionResult OnPost()
        {
            Categories = _context.Categories.ToList();
            Suppliers = _context.Suppliers.ToList();
            // Create the product
            int randomMonths = new Random().Next(3, 6);
            ExpirationDate = DateTime.Now.AddMonths(randomMonths);

            // Tạo sản phẩm
            Product.ExpirationDate = ExpirationDate;
            _productRepository.AddProduct(Product);

            // Create the purchase order
            PurchaseOrder purchaseOrder = new PurchaseOrder
            {
                SupplierId = SelectedSupplier,
                OrderDate = DateTime.Now, 
            };
            _context.PurchaseOrders.Add(purchaseOrder);
            _context.SaveChanges();

            // Create the purchase order item
            PurchaseOrderItem purchaseOrderItem = new PurchaseOrderItem
            {
                OrderId = purchaseOrder.OrderId,
                ProductId = Product.ProductId,
                Quantity = Product.QuantityInStock, 
                UnitPrice = PurchaseOrderUnitPrice,
            };
            _context.PurchaseOrderItems.Add(purchaseOrderItem);

            // Save changes to the database
        
            _context.SaveChanges();
            _hubContext.Clients.All.SendAsync("ReceiveChangeProduct");
            return RedirectToPage("List");
        }
    }
}

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using ProjectPRN221_Supermarket.Hubs;
using ProjectPRN221_Supermarket.Models;
using ProjectPRN221_Supermarket.Repository;

namespace ProjectPRN221_Supermarket.Pages.Products
{
    public class DeleteModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IHubContext<HubServer> _hubContext;
        public DeleteModel(IProductRepository productRepository, IHttpContextAccessor httpContextAccessor, IHubContext<HubServer> hubContext)
        {
            _productRepository = productRepository;
            _httpContextAccessor = httpContextAccessor;
            _hubContext = hubContext;
        }

        [BindProperty]
        public Product Product { get; set; }

        public IActionResult OnGet(int id)
        {
            var cashierId = _httpContextAccessor.HttpContext.Session.GetString("CashierId");

            // Kiểm tra xem có thông tin người dùng trong phiên không
            if (string.IsNullOrEmpty(cashierId))
            {
                return Redirect("/Login");
            }
            Product = _productRepository.GetProductById(id);
            if (Product == null)
            {
                return RedirectToPage("List");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            _productRepository.DeleteProduct(Product.ProductId);
            _hubContext.Clients.All.SendAsync("ReceiveChangeProduct");
            return RedirectToPage("List");
        }
    }
}

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using ProjectPRN221_Supermarket.Hubs;
using ProjectPRN221_Supermarket.Models;
using ProjectPRN221_Supermarket.Repository;

namespace ProjectPRN221_Supermarket.Pages.Products
{
	public class EditModel : PageModel
	{
		private readonly IProductRepository _productRepository;
		SupermarketDBContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IHubContext<HubServer> _hubContext;
        public EditModel(IProductRepository productRepository, SupermarketDBContext context, IHttpContextAccessor httpContextAccessor, IHubContext<HubServer> hubContext)
		{
			_productRepository = productRepository;
			_context = context;
			_httpContextAccessor = httpContextAccessor;
			_hubContext = hubContext;
		}

		[BindProperty]
		public Product Product { get; set; }
		public List<Category> Categories { get; set; }

		public IActionResult OnGet(int id)
		{
            var cashierId = _httpContextAccessor.HttpContext.Session.GetString("CashierId");

            // Kiểm tra xem có thông tin người dùng trong phiên không
            if (string.IsNullOrEmpty(cashierId))
            {
                // Chuyển hướng đến trang đăng nhập nếu chưa đăng nhập
                return Redirect("/Login");
            }
            Product = _productRepository.GetProductById(id);
			if (Product == null)
			{
				return RedirectToPage("List");
			}
			Categories = _context.Categories.ToList();
			return Page();
		}

		public IActionResult OnPost()
		{

			if (!ModelState.IsValid)
			{
				// Load the original product and related purchase order item from the database
				var originalProduct = _context.Products
					.Include(p => p.PurchaseOrderItems)
					.FirstOrDefault(p => p.ProductId == Product.ProductId);

				if (originalProduct == null)
				{
					return RedirectToPage("List");
				}

				// Check and update UnitPrice
				if (Product.UnitPrice < originalProduct.PurchaseOrderItems.Sum(poi => poi.UnitPrice))
				{
					ModelState.AddModelError("Product.UnitPrice", "UnitPrice cannot be less than the total UnitPrice of related PurchaseOrderItems.");
					Categories = _context.Categories.ToList();
					return Page();
				}

				// Check and update QuantityInStock
				if (Product.QuantityInStock > originalProduct.PurchaseOrderItems.Sum(poi => poi.Quantity))
				{
					ModelState.AddModelError("Product.QuantityInStock", "QuantityInStock cannot be greater than the total Quantity of related PurchaseOrderItems.");
					Categories = _context.Categories.ToList();
					return Page();
				}

				// Update the product
				originalProduct.ProductName = Product.ProductName;
				originalProduct.UnitPrice = Product.UnitPrice;
				originalProduct.QuantityInStock = Product.QuantityInStock;
				originalProduct.CategoryId = Product.CategoryId;

				_context.SaveChanges();
                _hubContext.Clients.All.SendAsync("ReceiveChangeProduct");
                return RedirectToPage("List");
			}

			Categories = _context.Categories.ToList();
			return Page();
		}
	}
}

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using ProjectPRN221_Supermarket.Hubs;
using ProjectPRN221_Supermarket.Models;
using ProjectPRN221_Supermarket.Pages.Paging;
using ProjectPRN221_Supermarket.Repository;
using ProjectPRN221_Supermarket.Service;

namespace ProjectPRN221_Supermarket.Pages.Products
{
    public class ListModel : PageModel
    {
        private readonly CartService _cartService;
        private SupermarketDBContext _context;
        private readonly IProductRepository _productRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IHubContext<HubServer> _hubContext;
        public ListModel(SupermarketDBContext context, IProductRepository productRepository, CartService cartService, IHttpContextAccessor httpContextAccessor, IHubContext<HubServer> hubContext)
        {
            _context = context;
            _productRepository = productRepository;
            _cartService = cartService;
            _httpContextAccessor = httpContextAccessor;
            _hubContext = hubContext;
        }
        [BindProperty]
        public PaginatedList<Product> Products { get; set; }
        public List<Category> Categories { get; set; }
        [BindProperty(SupportsGet = true)]
        public string productName { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? categoryId { get; set; }
        public IList<Product> Product { get; set; } = default!;
        public List<Product> ExpiringProducts { get; set; }
        public List<CartItem> CartItems { get; set; }
        public async Task<IActionResult> OnGet(int? pageIndex)
        {
            var cashierId = _httpContextAccessor.HttpContext.Session.GetString("CashierId");

            // Kiểm tra xem có thông tin người dùng trong phiên không
            if (string.IsNullOrEmpty(cashierId))
            {
                // Chuyển hướng đến trang đăng nhập nếu chưa đăng nhập
                return Redirect("/Login");
            }
            var pageSize = 4;
            IQueryable<Product> products = _context.Products.Include(c => c.Category).Include(p => p.PurchaseOrderItems).AsNoTracking();
            products = products.OrderBy(p => p.ExpirationDate).ThenByDescending(p => p.QuantityInStock);
            Products = await PaginatedList<Product>.CreateAsync(
                products, pageIndex ?? 1, pageSize);
            Categories = _context.Categories.ToList();
            CartItems = _cartService.GetCart();
            return Page();
        }
        public async Task OnPost(string productName, int? categoryId)
        {
            var query = _context.Products.Include(c => c.Category).AsQueryable();

            if (!string.IsNullOrEmpty(productName))
            {
                query = query.Where(p => p.ProductName.Contains(productName));
            }

            if (categoryId.HasValue && categoryId > 0)
            {
                query = query.Where(p => p.CategoryId == categoryId);
            }

            Products = await PaginatedList<Product>.CreateAsync(query, 1, 4);
            Categories = _context.Categories.ToList();
            CartItems = _cartService.GetCart();
        }
        public IActionResult OnPostAddToCart(int productId, string productName, decimal price, int quantity, int? pageIndex)
        {
               var cashierId = int.Parse(_httpContextAccessor.HttpContext.Session.GetString("CashierId"));
            // Lấy thông tin sản phẩm từ cơ sở dữ liệu
            var product = _context.Products.Find(productId);
            CartItems = _cartService.GetCart();
            // Kiểm tra nếu sản phẩm không tồn tại
            if (product == null)
            {
                return NotFound();
            }

            // Thêm sản phẩm vào giỏ hàng
            var cartProduct = new Product
            {
                ProductId = productId,
                ProductName = productName,
                UnitPrice = price,
                QuantityInStock = quantity,
            };
            var totalQuantityInCart = CartItems
         .Where(item => item.ProductItem.ProductId == productId)
         .Sum(item => item.Quantity);

            if (totalQuantityInCart >= product.QuantityInStock)
            {
                TempData["OutOfStockMessage"] = $"Quantity exceeds the available stock for product '{productName}'.";
                _hubContext.Clients.All.SendAsync("ReceiveOutOfStockMessage", TempData["OutOfStockMessage"]);
                return RedirectToPage("/Products/List");
            }

            if (product.QuantityInStock <= 0)
            {
                TempData["OutOfStockMessage"] = $"Product '{cartProduct.ProductName}' is out of stock.";
                _hubContext.Clients.All.SendAsync("ReceiveOutOfStockMessage", TempData["OutOfStockMessage"]);
                return RedirectToPage("/Products/List");
            }

            _cartService.AddToCart(cashierId, cartProduct);

            // Chuyển hướng về trang giỏ hàng
            return RedirectToPage("/Products/List", new { pageIndex });
        }

        public IActionResult OnPostClearCart()
        {
            // Xóa giỏ hàng
            _cartService.ClearCart();

            // Chuyển hướng về trang chủ
            return RedirectToPage("/Products/List");
        }
        public IActionResult OnPostCreateOrder()
        {
            var cashierId = _httpContextAccessor.HttpContext.Session.GetString("CashierId");

            // Kiểm tra xem có thông tin người dùng trong phiên không
            if (string.IsNullOrEmpty(cashierId))
            {
                // Chuyển hướng đến trang đăng nhập nếu chưa đăng nhập
                return Redirect("/Login");
            }

            // Chuyển CashierId từ string sang int
            if (!int.TryParse(cashierId, out int cashierIdInt))
            {
                return BadRequest("Invalid CashierId");
            }

            CartItems = _cartService.GetCart();

            // Kiểm tra xem có sản phẩm trong giỏ hàng hết hàng không
            foreach (var cartItem in CartItems)
            {
                var product = _context.Products.Find(cartItem.ProductItem.ProductId);
                if (product != null && product.QuantityInStock < cartItem.Quantity)
                {
                    // Nếu có ít nhất một sản phẩm trong giỏ hàng hết hàng, thông báo và không tạo đơn hàng
                    TempData["OutOfStockMessage"] = $"Product '{cartItem.ProductItem.ProductName}' is out of stock.";
                    _hubContext.Clients.All.SendAsync("ReceiveOutOfStockMessage", TempData["OutOfStockMessage"]);
                    return RedirectToPage("/Products/List");
                }
            }
            var order = new SalesOrder
            {
                CashierId = cashierIdInt,
                OrderDate = DateTime.Now,
                TotalAmount = CalculateTotalAmount(CartItems)
            };

            _context.SalesOrders.Add(order);
            _context.SaveChanges();

            // Tạo chi tiết đơn hàng (OrderDetail) cho từng sản phẩm trong giỏ hàng
            foreach (var cartItem in CartItems)
            {
                // Giảm số lượng tồn kho chỉ nếu sản phẩm có sẵn
                var product = _context.Products.Find(cartItem.ProductItem.ProductId);
                if (product != null)
                {
                    product.QuantityInStock -= cartItem.Quantity;
                }

                var orderDetail = new SalesOrderItem
                {
                    OrderId = order.OrderId,
                    ProductId = cartItem.ProductItem.ProductId,
                    Quantity = cartItem.Quantity,
                    UnitPrice = cartItem.Quantity * cartItem.ProductItem.UnitPrice
                };
                _context.SalesOrderItems.Add(orderDetail);
            }

            _context.SaveChanges();
            // Xóa sản phẩm khỏi giỏ hàng sau khi tạo đơn hàng
            _cartService.ClearCart();
            _hubContext.Clients.All.SendAsync("ReceiveSalesUpdate");
            return RedirectToPage("/SellProduct/SalesList");
        }

        private decimal CalculateTotalAmount(List<CartItem> cartItems)
        {
            decimal totalAmount = 0;
            foreach (var item in cartItems)
            {
                totalAmount += item.Quantity * item.ProductItem.UnitPrice;
            }
            return totalAmount;
        }
    }
}

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/Add.cshtml
@page
@model ProjectPRN221_Supermarket.Pages.Products.AddModel
@{
    ViewData["Title"] = "Add";
}

<h2>Add New Product</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Product.ProductName" class="control-label"></label>
        <input asp-for="Product.ProductName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Product.UnitPrice" class="control-label"></label>
        <input asp-for="Product.UnitPrice" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Product.QuantityInStock" class="control-label"></label>
        <input asp-for="Product.QuantityInStock" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Product.Category" class="control-label"></label>
        <select asp-for="Product.CategoryId" class="form-control">
            <option value="">Select Category</option>
            @foreach (var category in Model.Categories)
            {
                <option value="@category.CategoryId">@category.CategoryName</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label asp-for="SelectedSupplier" class="control-label">Select Supplier</label>
        <select asp-for="SelectedSupplier" class="form-control">
            <option value="">Select Supplier</option>
            @foreach (var supplier in Model.Suppliers)
            {
                <option value="@supplier.SupplierId">@supplier.SupplierName</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label asp-for="PurchaseOrderUnitPrice" class="control-label">Unit Price for Purchase Order</label>
        <input asp-for="PurchaseOrderUnitPrice" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Add</button>
</form>

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/Delete.cshtml
@page
@model ProjectPRN221_Supermarket.Pages.Products.DeleteModel
@{
    ViewData["Title"] = "Delete Product";
}

<h2>Delete Product</h2>

<form method="post">
    <input type="hidden" asp-for="Product.ProductId" />
    <div class="form-group">
        <label asp-for="Product.ProductName" class="control-label"></label>
        <input asp-for="Product.ProductName" class="form-control" disabled />
    </div>
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/Edit.cshtml
@page
@model ProjectPRN221_Supermarket.Pages.Products.EditModel
@{
    ViewData["Title"] = "Edit Product";
}

<h2>Edit Product</h2>
<form method="post">
    <input type="hidden" asp-for="Product.ProductId" />
    
    <div class="form-group">
        <label asp-for="Product.ProductName" class="control-label"></label>
        <input asp-for="Product.ProductName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Product.UnitPrice" class="control-label"></label>
        <input asp-for="Product.UnitPrice" class="form-control" />
        <span asp-validation-for="Product.UnitPrice" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Product.QuantityInStock" class="control-label"></label>
        <input asp-for="Product.QuantityInStock" class="form-control" />
        <span asp-validation-for="Product.QuantityInStock" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Product.Category" class="control-label"></label>
        <select asp-for="Product.CategoryId" class="form-control">
            <option value="">Select Category</option>
            @foreach (var category in Model.Categories)
            {
                <option value="@category.CategoryId">@category.CategoryName</option>
            }
        </select>
    </div>
    
    <button type="submit" class="btn btn-primary">Update</button>
</form>

ProjectPRN221_Supermarket/ProjectPRN221_Supermarket/Pages/Products/List.cshtml
@page
@model ProjectPRN221_Supermarket.Pages.Products.ListModel
@{
}
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th {
        background-color: #f2f2f2;
        font-weight: bold;
        text-align: left;
        padding: 10px;
    }

    td {
        padding: 8px;
        border-bottom: 1px solid #ccc;
    }
    h2 {
        font-size: 24px;
        margin-bottom: 20px;
    }

    .search-container {
        display: flex;
        align-items: center;
    }

    .search-left {
        flex: 1;
    }

    .search-right {
        margin-left: auto;
    }

</style>
<div>
	<h2>List of Products</h2>
    <form method="post">
        <div class="search-container">
            <div class="search-left">
                <label for="productName">Product Name:</label>
                <input type="text" id="productName" name="productName" asp-for="productName"/>
                <button type="submit">Search</button>
            </div>
            <div class="search-right">
                <label for="categoryId">Category:</label>
                <select id="categoryId" name="categoryId" onchange="submitForm()" asp-for="categoryId">
                    <option value="">All</option>
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.CategoryId">@category.CategoryName</option>
                    }
                </select>
            </div>
        </div>
    </form>
	<table>
		<thead>
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Sales Unit Price</th>
                <th>Import Unit Price</th>
				<th>Quantity</th>
				<th>Expired Date</th>
                <th>Days Left</th>
                <th>Warning</th>
				<th>Category</th>
                <th>Action</th>
                <th></th>
			</tr>
		</thead>
		<tbody>
		@foreach(var product in Model.Products)
		{
			<tr>
				<td> @product.ProductId</td>
				<td> @product.ProductName</td>
				<td> @product.UnitPrice</td>
                 <td>@product.PurchaseOrderItems.FirstOrDefault()?.UnitPrice</td>
				<td> @product.QuantityInStock</td>
				<td> @product.ExpirationDate?.ToString("dd/MM/yyyy")</td>
                <td>@((product.ExpirationDate - DateTime.Now)?.Days)</td>
                 <td>@((product.ExpirationDate - DateTime.Now)?.Days < 7 ? "Expiring Soon" : "")</td>
				<td> @product.Category.CategoryName</td>
                <td>
                        <a asp-page="/Products/Edit" asp-route-id="@product.ProductId">Edit</a> |
                        <a asp-page="/Products/Delete" asp-route-id="@product.ProductId">Delete</a>
                </td>
                    <td>
                        <form method="post" asp-page-handler="AddToCart">
                            <input type="hidden" name="productId" value="@product.ProductId" />
                            <input type="hidden" name="productName" value="@product.ProductName" />
                            <input type="hidden" name="price" value="@product.UnitPrice" />
                            <input type="hidden" name="pageIndex" value="@Model.Products.PageIndex"/>
                            <button type="submit">Add to Cart</button>
                        </form>
                    </td>
			</tr>
		}
		</tbody>
	</table>
</div>
@{
    var prevDisabled = !Model.Products.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Products.HasNextPage ? "disabled" : "";
}
<a asp-page="./List"
   asp-route-pageIndex="@(Model.Products.PageIndex - 1)"
   class="btn btn-primary @prevDisabled">
    Previous
</a>
<a asp-page="./List"
   asp-route-pageIndex="@(Model.Products.PageIndex + 1)"
   class="btn btn-primary @nextDisabled">
    Next
</a>
<script>
    function submitForm() {
        document.querySelector('form').submit();
    }
</script>
<h1>Sale</h1>
<table>
    <thead>
        <tr>
            <th>Product Id</th>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.CartItems != null)
        {
            @foreach (var item in Model.CartItems)
            {
                <tr>
                    <td>@item.ProductItem.ProductId</td>
                    <td>@item.ProductItem.ProductName</td>
                    <td>@item.Quantity</td>
                    <td>@item.ProductItem.UnitPrice</td>
                    <td>
                        <form method="post" asp-page-handler="AddToCart">
                            <input type="hidden" name="productId" value="@item.ProductItem.ProductId" />
                            <input type="hidden" name="productName" value="@item.ProductItem.ProductName" />
                            <input type="hidden" name="quantity" value="1" />
                            <input type="hidden" name="price" value="@item.ProductItem.UnitPrice" />
                        </form>
                    </td>
                </tr>
            }
        }
        else
        {
            <p>Cart is empty.</p>
        }
    </tbody>
</table>
@if (TempData["OutOfStockMessage"] != null)
{
    <div class="alert alert-warning" role="alert">
        @TempData["OutOfStockMessage"]
    </div>
}
<form method="post" asp-page-handler="ClearCart">
    <button type="submit">Clear Cart</button>
</form>
<form method="post" asp-page-handler="CreateOrder">
    <button type="submit">Place Order</button>
</form>
<script src="~/microsoft/signalr/dist/browser/signalr.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/sale.js" asp-append-version="true"></script>